### ISSUE TITLE
Error when merging Lora weights

### ISSUE THREAD

**Issue by hoangdzung** [eosphoros-ai/DB-GPT-Hub#127]
Thank you so much for your work. I'm trying to run `sh ./dbgpt_hub/scripts/export_merge.sh`, but getting the following error. Can you upload the latest script? Thanks.
```bash
Traceback (most recent call last):
  File "dbgpt_hub/train/export_model.py", line 14, in <module>
    main()
  File "dbgpt_hub/train/export_model.py", line 10, in main
    export_model()
  File "/home/DB-GPT-Hub/dbgpt_hub/llm_base/model_trainer.py", line 404, in export_model
    model_args, _, training_args, finetuning_args, _ = get_train_args(args, data_args_init=False)
  File "/home/DB-GPT-Hub/dbgpt_hub/llm_base/config_parser.py", line 111, in get_train_args
    ) = parse_train_args(args)
  File "/home/DB-GPT-Hub/dbgpt_hub/llm_base/config_parser.py", line 83, in parse_train_args
    return _parse_args(parser, args)
  File "/home/DB-GPT-Hub/dbgpt_hub/llm_base/config_parser.py", line 62, in _parse_args
    return parser.parse_args_into_dataclasses()
  File "/home/anaconda3/envs/dbgpt/lib/python3.8/site-packages/transformers/hf_argparser.py", line 347, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['-checkpoint_dir', '/home/CodeLlama-13b-sql-lora/']
```

**Comment by junewgl** [comment]
Can you provide specific information about your `export_merge.sh`? Are the weights based on our `train_sft.sh`? You can directly use the [huggingface](https://huggingface.co/Wangzaistone123/CodeLlama-13b-sql-lora) weights we uploaded. @hoangdzung
