### ISSUE TITLE
AttributeError: /home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_nf4

### ISSUE THREAD

**Issue by GuohuanFeng0** [eosphoros-ai/DB-GPT-Hub#137]
When i run poetry run sh dbgpt_hub/scripts/gen_train_eval_data.sh this i got this error (i just add this in the first line
--quantization_bit 4 \)

dbgpt_hub) dbgpt@anyi-Precision-5820-Tower-X-Series:~/DB-GPT-Hub$ poetry run sh dbgpt_hub/scripts/train_sft.sh
W&B offline. Running your script from this directory will only write metadata locally. Use wandb disabled to completely turn off W&B.
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/dbgpt/miniconda3/envs/dbgpt_hub did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('local/anyi-Precision-5820-Tower-X-Series'), PosixPath('@/tmp/.ICE-unix/2173,unix/anyi-Precision-5820-Tower-X-Series')}
  warn(msg)
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/0550f894_3e0e_46b6_872d_65c8b21dc743')}
  warn(msg)
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}
  warn(msg)
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
  warn(msg)
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
  warn(msg)
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[INFO|training_args.py:1332] 2023-11-14 10:51:03,355 >> Found safetensors installation, but --save_safetensors=False. Safetensors should be a preferred weights saving format due to security and performance reasons. If your model cannot be saved by safetensors please feel free to open an issue at https://github.com/huggingface/safetensors!
[INFO|training_args.py:1764] 2023-11-14 10:51:03,355 >> PyTorch: setting up devices
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/training_args.py:1677: FutureWarning: `--push_to_hub_token` is deprecated and will be removed in version 5 of 🤗 Transformers. Use `--hub_token` instead.
  warnings.warn(
/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/datasets/load.py:2089: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=None' instead.
  warnings.warn(
Using custom data configuration default-2e946045a3358c4c
Loading Dataset Infos from /home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/datasets/packaged_modules/json
Overwrite dataset info from restored data version if exists.
Loading Dataset info from /home/dbgpt/.cache/huggingface/datasets/json/default-2e946045a3358c4c/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
Found cached dataset json (/home/dbgpt/.cache/huggingface/datasets/json/default-2e946045a3358c4c/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
Loading Dataset info from /home/dbgpt/.cache/huggingface/datasets/json/default-2e946045a3358c4c/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
[INFO|tokenization_utils_base.py:1850] 2023-11-14 10:51:03,606 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:1850] 2023-11-14 10:51:03,607 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1850] 2023-11-14 10:51:03,607 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1850] 2023-11-14 10:51:03,607 >> loading file tokenizer_config.json
[INFO|configuration_utils.py:713] 2023-11-14 10:51:03,664 >> loading configuration file /home/dbgpt/DB-GPT0.39/models/Llama-2-13b-chat-hf/config.json
[INFO|configuration_utils.py:775] 2023-11-14 10:51:03,666 >> Model config LlamaConfig {
  "_name_or_path": "/home/dbgpt/DB-GPT0.39/models/Llama-2-13b-chat-hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 13824,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "num_key_value_heads": 40,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.33.2",
  "use_cache": true,
  "vocab_size": 32000
}

[INFO|modeling_utils.py:2866] 2023-11-14 10:51:03,692 >> loading weights file /home/dbgpt/DB-GPT0.39/models/Llama-2-13b-chat-hf/model.safetensors.index.json
[INFO|modeling_utils.py:1200] 2023-11-14 10:51:03,693 >> Instantiating LlamaForCausalLM model under default dtype torch.bfloat16.
[INFO|configuration_utils.py:768] 2023-11-14 10:51:03,693 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "transformers_version": "4.33.2"
}

[INFO|modeling_utils.py:2983] 2023-11-14 10:51:03,794 >> Detected 4-bit loading: activating 4-bit loading for this model
Loading checkpoint shards:   0%|                                                                                                    | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/dbgpt/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 165, in <module>
    train()
  File "/home/dbgpt/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 142, in train
    run_sft(
  File "/home/dbgpt/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 48, in run_sft
    model, tokenizer = load_model_and_tokenizer(
  File "/home/dbgpt/DB-GPT-Hub/dbgpt_hub/llm_base/load_tokenizer.py", line 258, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3187, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3575, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 753, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/integrations/bitsandbytes.py", line 98, in set_module_quantized_tensor_to_device
    new_value = bnb.nn.Params4bit(new_value, requires_grad=False, **kwargs).to(device)
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 176, in to
    return self.cuda(device)
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 154, in cuda
    w_4bit, quant_state = bnb.functional.quantize_4bit(w, blocksize=self.blocksize, compress_statistics=self.compress_statistics, quant_type=self.quant_type)
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/functional.py", line 776, in quantize_4bit
    lib.cquantize_blockwise_fp16_nf4(get_ptr(None), get_ptr(A), get_ptr(absmax), get_ptr(out), ct.c_int32(blocksize), ct.c_int(n))
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/dbgpt/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_nf4

**Comment by GuohuanFeng0** [comment]
Below is the content of my script
wandb offline # Close wandb
# a100 ,单卡
current_date=$(date +"%Y%m%d_%H%M")
train_log="dbgpt_hub/output/logs/train_sft_test_${current_date}.log"
start_time=$(date +%s)
echo " Train Start time: $(date -d @$start_time +'%Y-%m-%d %H:%M:%S')" >>${train_log}

# the default param set could be run in a server with one a100(40G) gpu, if your server not support the set,you can set smaller param such as  lora_rank and use qlora with quant 4 eg...
CUDA_VISIBLE_DEVICES=0 python dbgpt_hub/train/sft_train.py \
    --quantization_bit 4 \
    --model_name_or_path /home/dbgpt/DB-GPT0.39/models/Llama-2-13b-chat-hf \
    --do_train \
    --dataset example_text2sql_train \
    --max_source_length 2048 \
    --max_target_length 512 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --template llama2 \
    --lora_rank 64 \
    --lora_alpha 32 \
    --output_dir dbgpt_hub/output/adapter/Llama-2-13b-sql-lora \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine_with_restarts \
    --logging_steps 50 \
    --save_steps 2000 \
    --learning_rate 2e-4 \
    --num_train_epochs 8 \
    --plot_loss \
    --bf16  >> ${train_log}
    # --bf16#v100不支持bf16
    
echo "############train end###############" >>${train_log}
echo "Train End time: $(date)" >>${train_log}
end_time=$(date +%s)
duration=$((end_time - start_time))
hours=$((duration / 3600))
min=$(( (duration % 3600) / 60))
echo "Time elapsed: ${hour}  hour $min min " >>${train_log}


# 多卡，deepseed启动，A100
# deepspeed --num_gpus 2  dbgpt_hub/train/sft_train.py \
#     --deepspeed dbgpt_hub/configs/stage2.json \
#     --quantization_bit 4 \
#     --model_name_or_path /home/model_files/Llama-2-13b-chat-hf \
#     --do_train \
#     --dataset example_text2sql_train \
#     --max_source_length 1024 \
#     --max_target_length 512 \
#     --template llama2 \
#     --finetuning_type lora \
#     --lora_rank 64 \
#     -

Could u help me? @qidanrui

**Comment by GuohuanFeng0** [comment]
Below is the content of my script

```
wandb offline # Close wandb
# a100 ,单卡
current_date=$(date +"%Y%m%d_%H%M")
train_log="dbgpt_hub/output/logs/train_sft_test_${current_date}.log"
start_time=$(date +%s)
echo " Train Start time: $(date -d @$start_time +'%Y-%m-%d %H:%M:%S')" >>${train_log}

# the default param set could be run in a server with one a100(40G) gpu, if your server not support the set,you can set smaller param such as  lora_rank and use qlora with quant 4 eg...
CUDA_VISIBLE_DEVICES=0 python dbgpt_hub/train/sft_train.py \
    --quantization_bit 4 \
    --model_name_or_path /home/dbgpt/DB-GPT0.39/models/Llama-2-13b-chat-hf \
    --do_train \
    --dataset example_text2sql_train \
    --max_source_length 2048 \
    --max_target_length 512 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --template llama2 \
    --lora_rank 64 \
    --lora_alpha 32 \
    --output_dir dbgpt_hub/output/adapter/Llama-2-13b-sql-lora \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine_with_restarts \
    --logging_steps 50 \
    --save_steps 2000 \
    --learning_rate 2e-4 \
    --num_train_epochs 8 \
    --plot_loss \
    --bf16  >> ${train_log}
    # --bf16#v100不支持bf16
    
echo "############train end###############" >>${train_log}
echo "Train End time: $(date)" >>${train_log}
end_time=$(date +%s)
duration=$((end_time - start_time))
hours=$((duration / 3600))
min=$(( (duration % 3600) / 60))
echo "Time elapsed: ${hour}  hour $min min " >>${train_log}


# 多卡，deepseed启动，A100
# deepspeed --num_gpus 2  dbgpt_hub/train/sft_train.py \
#     --deepspeed dbgpt_hub/configs/stage2.json \
#     --quantization_bit 4 \
#     --model_name_or_path /home/model_files/Llama-2-13b-chat-hf \
#     --do_train \
#     --dataset example_text2sql_train \
#     --max_source_length 1024 \
#     --max_target_length 512 \
#     --template llama2 \
#     --finetuning_type lora \
#     --lora_rank 64 \
#     -
``` 
Could u help me @qidanrui

**Comment by qidanrui** [comment]
Hi @GuohuanFeng0, Could you please provide us your running environment ?

**Comment by GuohuanFeng0** [comment]
> Hi @GuohuanFeng0, Could you please provide us your running environment ?

Hi Dr.Rui this is my nvcc-version
(base) dbgpt@anyi-Precision-5820-Tower-X-Series:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

but i can't find any file when i use this commond
(base) dbgpt@anyi-Precision-5820-Tower-X-Series:~$ ls /usr/local/cuda/lib64/libcublas.so.*
ls: cannot access '/usr/local/cuda/lib64/libcublas.so.*': No such file or directory

(base) dbgpt@anyi-Precision-5820-Tower-X-Series:~$ ls /usr/local
bin  etc  games  include  lib  man  sbin  share  src
