### ISSUE TITLE
TypeError: Device() received an invalid combination of arguments - got (NoneType), but expected one of:  * (torch.device device)

### ISSUE THREAD

**Issue by sardetushar** [eosphoros-ai/DB-GPT-Hub#15]
```
(dbgpt_hub) tushar@TGL344:~/text2sql/DB-GPT-Hub$ python src/train/train_qlora.py --model_name_or_path falcon-rw-1b/

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
loading base model falcon-rw-1b/...
/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py:2193: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
adding LoRA modules...
trainable params: 25165824.0 || all params: 1361956864 || trainable: 1.8477695340577247
loaded model
/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1714: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Found cached dataset json (/home/tushar/.cache/huggingface/datasets/json/default-4e0c5450a5ca22bb/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.93it/s]
Loading cached processed dataset at /home/tushar/.cache/huggingface/datasets/json/default-4e0c5450a5ca22bb/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-18c92fe147e577b4.arrow
torch.float32 1361862656 1.0
Traceback (most recent call last):
  File "/home/tushar/text2sql/DB-GPT-Hub/src/train/train_qlora.py", line 832, in <module>
    train()
  File "/home/tushar/text2sql/DB-GPT-Hub/src/train/train_qlora.py", line 794, in train
    train_result = trainer.train()
  File "/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/trainer.py", line 1526, in train
    return inner_training_loop(
  File "/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/trainer.py", line 1643, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/accelerate/accelerator.py", line 1182, in prepare
    result = tuple(
  File "/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/accelerate/accelerator.py", line 1183, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/accelerate/accelerator.py", line 1022, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/tushar/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/accelerate/accelerator.py", line 1255, in prepare_model
    if torch.device(current_device_index) != self.device:
TypeError: Device() received an invalid combination of arguments - got (NoneType), but expected one of:
 * (torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType)
 * (str type, int index)
```

**Comment by wangzaistone** [comment]
It seems like cuda error，maybe this [similar issue ]( https://github.com/eosphoros-ai/DB-GPT-Hub/issues/9#issuecomment-1650994379)could be help ，
