### ISSUE TITLE
路径报错：[Errno 2] No such file or directory: 'dbgpt_hub/data/dataset_info.json'

### ISSUE THREAD

**Issue by polar-bear1234** [eosphoros-ai/DB-GPT-Hub#202]
/root/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
Traceback (most recent call last):
  File "/root/autodl-tmp/workspace/dbgpt/dbgpt_hub/scripts/../train/sft_train.py", line 165, in <module>
    train()
  File "/root/autodl-tmp/workspace/dbgpt/dbgpt_hub/scripts/../train/sft_train.py", line 139, in train
    ) = get_train_args(args)
  File "/root/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/dbgpt_hub/llm_base/config_parser.py", line 125, in get_train_args
    data_args.init_for_training()
  File "/root/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/dbgpt_hub/configs/data_args.py", line 167, in init_for_training
    with open(os.path.join(self.dataset_dir, "dataset_info.json"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dbgpt_hub/data/dataset_info.json'

**Comment by junewgl** [comment]
What is your running script? What are the running steps? @polar-bear1234

**Comment by LorenFeng** [comment]
我也出现了这个问题，怎么解决呢
