### ISSUE TITLE
An error occurred when finetune chatglm3

### ISSUE THREAD

**Issue by wwgnull** [eosphoros-ai/DB-GPT-Hub#211]
Traceback (most recent call last):
  File "/root/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 165, in <module>
    train()
  File "/root/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 142, in train
    run_sft(
  File "/root/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 48, in run_sft
    model, tokenizer = load_model_and_tokenizer(
  File "/root/DB-GPT-Hub/dbgpt_hub/llm_base/load_tokenizer.py", line 292, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3187, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3560, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 504, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/root/ChatGLM3/chatglm3-6b/pytorch_model-00001-of-00007.bin' at '/root/ChatGLM3/chatglm3-6b/pytorch_model-00001-of-00007.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by wwgnull** [comment]
The problem has been resolved, just download the model again.

**Comment by wangzaistone** [comment]
ok
