### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by wwgnull** [eosphoros-ai/DB-GPT-Hub#215]
报错如下：
Traceback (most recent call last):
  File "/root/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 165, in <module>
    train()
  File "/root/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 142, in train
    run_sft(
  File "/root/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 51, in run_sft
    dataset = preprocess_dataset(dataset, tokenizer, data_args, training_args, "sft")
  File "/root/DB-GPT-Hub/dbgpt_hub/data_process/data_utils.py", line 799, in preprocess_dataset
    dataset = dataset.map(
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3097, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3474, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/root/DB-GPT-Hub/dbgpt_hub/data_process/data_utils.py", line 653, in preprocess_supervised_dataset
    for source_ids, target_ids in template.encode_multiturn(
  File "/root/DB-GPT-Hub/dbgpt_hub/configs/data_args.py", line 270, in encode_multiturn
    encoded_pairs = self._encode(tokenizer, system, history)
  File "/root/DB-GPT-Hub/dbgpt_hub/configs/data_args.py", line 321, in _encode
    prefix_ids = self._convert_inputs_to_ids(
  File "/root/DB-GPT-Hub/dbgpt_hub/configs/data_args.py", line 368, in _convert_inputs_to_ids
    token_ids = token_ids + tokenizer.encode(elem, **kwargs)
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2373, in encode
    encoded_inputs = self.encode_plus(
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2781, in encode_plus
    return self._encode_plus(
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 659, in _encode_plus
    return self.prepare_for_model(
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3260, in prepare_for_model
    encoded_inputs = self.pad(
  File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3065, in pad
    encoded_inputs = self._pad(
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3_finetune/tokenization_chatglm.py", line 299, in _pad
    assert self.padding_side == "left"
AssertionError

**Comment by wwgnull** [comment]
问题已解决，将tokenization_chatglm.py中第299行assert self.padding_side == "left"中的left更改为right即可。
