### ISSUE TITLE
pip install dbgpt-hub Report an error

### ISSUE THREAD

**Issue by zhangkuo-zk** [eosphoros-ai/DB-GPT-Hub#264]
安装最新的dbgpt-hub依赖提示如下错误
![Uploading Snipaste_2024-04-28_17-50-55.png…]()

**Comment by zhangkuo-zk** [comment]
Collecting dbgpt-hub
  Using cached dbgpt_hub-0.3.1-py3-none-any.whl.metadata (26 kB)
Collecting accelerate==0.21.0 (from dbgpt-hub)
  Using cached accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)
Collecting bitsandbytes==0.41.2 (from dbgpt-hub)
  Using cached bitsandbytes-0.41.2-py3-none-any.whl.metadata (9.8 kB)
Collecting black<24.0.0,>=23.11.0 (from dbgpt-hub)
  Using cached black-23.12.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (68 kB)
Collecting datasets>=2.12.0 (from dbgpt-hub)
  Using cached datasets-2.19.0-py3-none-any.whl.metadata (19 kB)
Collecting deepspeed==0.10.2 (from dbgpt-hub)
  Using cached deepspeed-0.10.2.tar.gz (858 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/3q/dtdsy_dd16s78m837rqcf36h0000gn/T/pip-install-li2eivro/deepspeed_46c0d2164dc149c28f6ee1fc8608b88c/setup.py", line 38, in <module>
          from op_builder.all_ops import ALL_OPS
        File "/private/var/folders/3q/dtdsy_dd16s78m837rqcf36h0000gn/T/pip-install-li2eivro/deepspeed_46c0d2164dc149c28f6ee1fc8608b88c/op_builder/all_ops.py", line 18, in <module>
          op_builder_dir = get_accelerator().op_builder_dir()
        File "/private/var/folders/3q/dtdsy_dd16s78m837rqcf36h0000gn/T/pip-install-li2eivro/deepspeed_46c0d2164dc149c28f6ee1fc8608b88c/accelerator/real_accelerator.py", line 155, in get_accelerator
          ds_accelerator = MPS_Accelerator()
      TypeError: Can't instantiate abstract class MPS_Accelerator with abstract method supported_dtypes
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by iLampard** [comment]
Hi, 

Have your problem fixed?

can you have a look at this [issue](https://github.com/microsoft/DeepSpeed/issues/5132) from deepspeed to see if you can fix it.

**Comment by zhangkuo-zk** [comment]
Thank you iLampard
