### ISSUE TITLE
predict_sft.sh中参数如何填写，多次尝试运行脚本文件都报错

### ISSUE THREAD

**Issue by Oops322** [eosphoros-ai/DB-GPT-Hub#275]
我的predict_sft.sh关键参数部分如下
CUDA_VISIBLE_DEVICES=0  python dbgpt_hub/predict/predict.py \
    --quantization_bit 4 \
    --model_name_or_path /mnt/model/Llama-2-7b-chat-hf \     #①
    --template llama2 \
    --finetuning_type lora \
    --predicted_input_filename dbgpt_hub/data/example_text2sql_dev.json \
    --checkpoint_dir /mnt/output/adapter/Llama-2-7b-chat-hf \     #②
    --predicted_out_filename /mnt/output/pred/pred_fine-tunedLlama.sql >> ${pred_log}

①原始的未经操作的llama2-7b
②这个参数一直不知道要注释掉还是怎么填，现在填的是经过train_sft.sh微调大模型后生成的文件，内含文件如下
adapter_config.json  all_results.json      README.md          trainer_state.json  training_loss.png
adapter_model.bin    finetuning_args.json  trainer_log.jsonl  training_args.bin   train_results.json

照这么执行poetry run sh ./dbgpt_hub/scripts/predict_sft.sh的话，会得到如下报错：
    /home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████| 2/2 [01:22<00:00, 41.49s/it]Traceback (most recent call last):
  File "/home/moonlight/Projects//Text-to-Sql/DB-GPT-Hub/dbgpt_hub/predict/predict.py", line 50, in <module>
    model = ChatModel()
  File "/home/moonlight/Projects//Text-to-Sql/DB-GPT-Hub/dbgpt_hub/llm_base/chat_model.py", line 21, in __init__
    self.model, self.tokenizer = load_model_and_tokenizer(
  File "/home/moonlight/Projects//Text-to-Sql/DB-GPT-Hub/dbgpt_hub/llm_base/load_tokenizer.py", line 328, in load_model_and_tokenizer
    model = init_adapter(model, model_args, finetuning_args, is_trainable, is_mergeable)
  File "/home/moonlight/Projects//Text-to-Sql/DB-GPT-Hub/dbgpt_hub/llm_base/adapter.py", line 94, in init_adapter
    model = PeftModel.from_pretrained(
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/peft_model.py", line 271, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/peft_model.py", line 561, in load_adapter
    load_result = set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 126, in set_peft_model_state_dict
    load_result = model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2138, in load_state_dict
    load(self, state_dict)
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  [Previous line repeated 4 more times]
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2120, in load
    module._load_from_state_dict(
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 256, in _load_from_state_dict
    self.weight, state_dict = bnb.nn.Params4bit.from_state_dict(
  File "/home/moonlight/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 158, in from_state_dict
    data = state_dict.pop(prefix.rstrip('.'))
KeyError: 'base_model.model.model.layers.0.self_attn.q_proj.weight'

又或者①填的是模型和微调权重合并后的模型llama-fine-tuned，然后②注释掉
这样能运行，但最后得到的sql文件里是乱码，用poetry run python dbgpt_hub/eval/evaluation.py --plug_value --input  Your_model_pred_file一评估全是0...   sql文件内容如下：
![QQ截图20240703094508](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/170330071/c4adcf9e-be5f-460c-a7b8-5eb9c2abfe1c)

**Comment by Oops322** [comment]
执行了以下命令后查看adapter_model.bin内容得到如图：
import torch
state_dict = torch.load('...../adapter_model.bin')
print(state_dict.keys())
![QQ截图20240703101357](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/170330071/5d3a8089-dbc1-4ab2-9266-26729b52979f)
这跟“base_model.model.model.layers.0.self_attn.q_proj.weight”这个报错的关系是什么呢

**Comment by Oops322** [comment]
微调时train_sft.sh内的参数如下：
CUDA_VISIBLE_DEVICES=0 python dbgpt_hub/train/sft_train.py \
    --quantization_bit 4 \
    --model_name_or_path $model_name_or_path \
    --do_train \
    --dataset $dataset \
    --max_source_length 1024 \
    --max_target_length 512 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --template llama2 \
    --lora_rank 32 \
    --lora_alpha 16 \
    --output_dir $output_dir \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine_with_restarts \
    --logging_steps 50 \
    --save_steps 2000 \
    --learning_rate 2e-4 \
    --num_train_epochs 4 \
    --plot_loss \
    --fp16  >> ${train_log}
    #--bf16  >> ${train_log}

**Comment by Oops322** [comment]
现在发现了，export_merge.sh里加上--quantization_bit 4 \ 就会开始报错KeyError: 'base_model.model.model.layers.0.self_attn.q_proj.weight'了，估计合并权重的模型之所以输出乱七八糟就是因为当时合并权重没有加--quantization_bit 4 \ 才得以顺利执行，导致新形成的模型本身就有问题

**Comment by Oops322** [comment]
在师兄指导下得知不要随便执行export_merge.sh。。 不懂原理，一顿瞎操作把我的adapter下的bin文件估计给弄坏了 重新train一遍再操作吧

**Comment by Oops322** [comment]
解决KeyError: 'base_model.model.model.layers.0.self_attn.q_proj.weight'的办法：将bitsandbytes的版本从0.41.2降到0.41.1，亲测有效，估计是这个依赖跟peft依赖有冲突。经此方法后predict步骤顺利执行。
解决sql内容乱七八糟的方法：换个好点的显卡，提高train_sft.sh内的部分参数，训练一个好点的模型权重出来。

**Comment by thunder95** [comment]
大佬是怎么解决的，评估全是0
