### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.deepspeed'，已经安装了transformers和deepspeed 

### ISSUE THREAD

**Issue by xiangzhangpang** [eosphoros-ai/DB-GPT-Hub#295]
已经安装了transformers 4.46.0 ，deepspeed 0.15.3，报错
Traceback (most recent call last):
  File "/DB-GPT-Hub/src/dbgpt_hub_sql/train/sft_train.py", line 15, in <module>
    from dbgpt_hub_sql.llm_base.load_tokenizer import load_model_and_tokenizer
  File "/DB-GPT-Hub/src/dbgpt_hub_sql/llm_base/load_tokenizer.py", line 18, in <module>
    from transformers.deepspeed import is_deepspeed_zero3_enabled
ModuleNotFoundError: No module named 'transformers.deepspeed'
有没有大佬知道要怎么解决

**Comment by SakuraRan-X** [comment]
new version：

from transformers.integrations.deepspeed import is_deepspeed_zero3_enabled

**Comment by gerogexiongle** [comment]
我也遇到了    from transformers.deepspeed import is_deepspeed_zero3_enabled
ModuleNotFoundError: No module named 'transformers.deepspeed'
