### ISSUE TITLE
ImportError: cannot import name 'is_npu_available' from 'accelerate.utils

### ISSUE THREAD

**Issue by csunny** [eosphoros-ai/DB-GPT-Hub#42]
When run train_lora.py, this error occur.
```
[2023-08-06 16:20:02,695] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/magic/workspace/github/DB-GPT-Hub/train_lora.py", line 11, in <module>
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
  File "/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/auto.py", line 30, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/mapping.py", line 20, in <module>
    from .peft_model import (
  File "/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/peft_model.py", line 39, in <module>
    from .tuners import (
  File "/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/tuners/__init__.py", line 20, in <module>
    from .adaption_prompt import AdaptionPromptConfig, AdaptionPromptModel
  File "/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/tuners/adaption_prompt.py", line 25, in <module>
    from peft.utils.config import PeftConfig, PeftType
  File "/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/utils/__init__.py", line 20, in <module>
    from .config import PeftConfig, PeftType, PromptLearningConfig, TaskType
  File "/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/utils/config.py", line 25, in <module>
    from .other import CONFIG_NAME
  File "/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/utils/other.py", line 24, in <module>
    from accelerate.utils import is_npu_available, is_xpu_available
ImportError: cannot import name 'is_npu_available' from 'accelerate.utils' (/home/magic/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/accelerate/utils/__init__.py)
```
The accelerate version should > 0.21, i will fix this later

**Comment by ponyzym** [comment]
conda install accelerate==?
