### ISSUE TITLE
根据文档部署，无法正确安装依赖

### ISSUE THREAD

**Issue by shouziws** [eosphoros-ai/DB-GPT-Hub#64]
我的电脑环境
操作系统：Windows 10
Python环境：没有安装Python全程由conda接管的python环境

以下是部署流程
1：git clone https://github.com/eosphoros-ai/DB-GPT-Hub.git
2：cd DB-GPT-Hub
3：conda create -n dbgpt_hub python=3.10 
4：conda activate dbgpt_hub
5：pip install -r requirements.txt 
6：mkdir model 

在我执行到以上第五步时出现了以下报错
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/33045888/cfb89d83-896a-479b-abf8-6ded2c5ed85c)
`Using cached deepspeed-0.10.1.tar.gz (851 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-2yh9rcbk\deepspeed_a9c7d8ac102d47cb98e3333637167093\setup.py", line 130, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
      [93m [WARNING] [0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

根据报错信息，是提醒的是 "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops." 让我安装torch，我手动执行了一次 “pip install torch”，执行完毕之后再重新输入" pip install -r requirements.txt"出现以下报错
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/33045888/b0c61fad-ff41-48bf-ab82-6df77b278b7d)
`  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-k20092eq\deepspeed_e5873407e1024ede871551fd95a1652d\setup.py", line 165, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-k20092eq\deepspeed_e5873407e1024ede871551fd95a1652d\setup.py", line 51, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(dbgpt_hub) D:\Project\company\DB-GPT-Hub>`
请问我应该如何解决

**Comment by junewgl** [comment]
This seems to be the cause of AMD GPU hardware, you can try using our suggested [AutoDL](https://www.autodl.com/console/instance/list) method.
