### ISSUE TITLE
Can't find 'adapter_config.json' at './adapter/adapter_model'

### ISSUE THREAD

**Issue by Matter-Charles** [eosphoros-ai/DB-GPT-Hub#71]
想问一下在跑完微调后想要跑预测，发现了这个报错：Can't find 'adapter_config.json' at './adapter/adapter_model'。这个文件是在哪里生成的？adapter文件夹里面没有发现，我填写的是 --peft_ckpt_path ./adapter，报错里面的'./adapter/adapter_model'没有这个文件夹，请问是怎么生成的路径？

**Comment by wangzaistone** [comment]
i

> Traceback (most recent call last): File "/root/xx/DB-GPT-Hub/predict_qlora.py", line 233, in dataset_name, result = predict() File "/root/xx/DB-GPT-Hub/predict_qlora.py", line 109, in predict ) = parser.parse_args_into_dataclasses() File "/root/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/hf_argparser.py", line 347, in parse_args_into_dataclasses raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}") ValueError: Some specified arguments are not used by the HfArgumentParser: ['--peft_ckpt_path', 'adapterqlora']

if not works , you can difine the model path in the predict_qlora.py , the function :
"
def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--base_model_name_or_path",
        type=str,
        default="/home/model_files/Llama-2-13b-chat-hf",
    )
    parser.add_argument(
        "--peft_ckpt_path",
        type=str,
        default="/home/LLM/DB-GPT-Hub/llama_adapter/qlora_32_lr_2e4_drop1e1/checkpoint-500",
.....
"
